export const FORM_CHANGE_DEFAULT = 'FORM_CHANGE_DEFAULT';
export const FORM_CHANGE_LABEL = 'FORM_CHANGE_LABEL';
export const FORM_CHANGE_ORDER = 'FORM_CHANGE_ORDER';
export const FORM_POST = 'FORM_POST';
export const FORM_SET_CHOICES = 'FORM_SET_CHOICES';
export const FORM_SET_INVALID = 'FORM_SET_INVALID';
