export const FORM_CHANGE_LABEL = 'FORM_CHANGE_LABEL';
export const FORM_CHANGE_ORDER = 'FORM_CHANGE_ORDER';
export const FORM_SET_INVALID = 'FORM_SET_INVALID';
export const FORM_SET_CHOICES = 'FORM_SET_CHOICES';
